### ISSUE TITLE
Still Supported

### ISSUE THREAD

**Issue by markriggins** [localytics/stager-server#3]
Hi,

Looks interesting -- but I don't see any recent commits.   Is this still supported?   Has it gathered much interest?

Mark

**Comment by beezee** [comment]
Hi Mark.

I can only hope the quiet means it's just so good nobody has had an issue :)

I can say that it's still humming along as a key part of Localytics delivery pipeline. It's a fairly focused tool so I don't personally have a vivid imagination about what kind of feature additions would be high priority.

Is there something particular you are concerned about besides commit activity?

**Comment by markriggins** [comment]
I'm working on a tool that serves a similar purpose, but has a
vastly-different interface and implementation.

I'm seeking permission to open source  my own tool,  so I was wondering if
you were getting any outside interest.

Mark

**Comment by beezee** [comment]
Very few of the stars on this repo came from folks at Localytics, so I suppose that's the closest to actual data I can give you.

Good luck with your project, I'll close this issue now.
